version: '3.5'
services:
  app:
    container_name: sys_controla_pet
    image: controlapet:develop
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - mysql:mysql
    networks:
      - controlapet
    depends_on:
      - migration
      - mysql

  collectstatic:
    container_name: collectstatic
    image: controlapet:develop
    build:
      context: .
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/app
    networks:
      - controlapet
    depends_on:
      - mysql

  migration:
    container_name: migration
    image: controlapet:develop
    build:
      context: .
    command: python manage.py migrate
    volumes:
      - .:/app
    networks:
      - controlapet
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=Morumbichos
      - MYSQL_ROOT_PASSWORD=SysControlaPet2018
    volumes:
      - .:/app
    ports:
      - 3308:3306
    networks:
      - controlapet

networks:
  controlapet:
    external:
      name: controlapet
