version: '3.5'
services:
  app:
    container_name: sys_controla_pet
    image: controlapet:develop
    build:
      context: .
    command: >
      bash -c "find /app -name '000*.py' -delete
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py shell -c "from usuarios.models import User; User.objects.create_superuser(login='controla.pet', primeiro_nome='controla', ultimo_nome='pet', password='SysControlaPet@2018')"
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - mysql:aquelea01
    networks:
      - controlapet
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=Morumbichos
      - MYSQL_ROOT_PASSWORD=SysControlaPet2018
    ports:
      - 3308:3306
    networks:
      - controlapet

networks:
  controlapet:
    external:
      name: controlapet
