# Generated by Django 2.0.6 on 2018-06-15 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_auto_20180615_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioAbstrato',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('equipe_sistema', models.BooleanField(verbose_name='tem acesso ao sistema?')),
            ],
            options={
                'abstract': False,
            },
            bases=('usuarios.user',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcionarioabstrato_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funcionarios.FuncionarioAbstrato')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
            ],
            options={
                'abstract': False,
            },
            bases=('funcionarios.funcionarioabstrato',),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('funcionarioabstrato_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funcionarios.FuncionarioAbstrato')),
                ('crm', models.CharField(max_length=50, unique=True, verbose_name='CRM')),
                ('estado_emissor', models.CharField(max_length=2, verbose_name='Estado Emissor')),
            ],
            options={
                'abstract': False,
            },
            bases=('funcionarios.funcionarioabstrato',),
        ),
    ]
