# Generated by Django 2.0.6 on 2018-06-17 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('equipe_sistema', models.BooleanField(verbose_name='tem acesso ao sistema?')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.CargoFuncionario', verbose_name='Cargo')),
            ],
            options={
                'abstract': False,
            },
            bases=('usuarios.user', models.Model),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('equipe_sistema', models.BooleanField(verbose_name='tem acesso ao sistema?')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Primeiro nome')),
                ('ultimo_nome', models.CharField(max_length=50, verbose_name='Último nome')),
                ('crm', models.CharField(max_length=50, unique=True, verbose_name='CRM')),
                ('estado_emissor', models.CharField(max_length=2, verbose_name='Estado Emissor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
