# Generated by Django 2.0.6 on 2018-07-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'ANIMAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('numero', models.SmallIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TIPO_CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoStatusAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TIPO_STATUS_ANIMAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaAnimal',
            fields=[
                ('id_animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cliente.Animal')),
                ('data_consulta', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'FICHA_ANIMAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusAnimal',
            fields=[
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cliente.TipoStatusAnimal')),
            ],
            options={
                'db_table': 'STATUS_ANIMAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('cpf_cliente', models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cliente.Cliente')),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'TELEFONE_CLIENTE',
                'managed': False,
            },
        ),
    ]
