# Generated by Django 2.0.6 on 2018-10-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.CharField(blank=True, max_length=500, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'db_table': 'ANIMAL',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('url_foto', models.CharField(blank=True, max_length=500, null=True)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('numero', models.SmallIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='FichaAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField(blank=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('id_animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Animal')),
            ],
            options={
                'verbose_name': 'Ficha do Animal',
                'verbose_name_plural': 'Fichas dos Animais',
                'db_table': 'FICHA_ANIMAL',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'db_table': 'RESPONSAVEL',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Clientes',
                'db_table': 'TIPO_CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='TipoStatusAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Status do Animal',
                'verbose_name_plural': 'Tipos de Status dos Animais',
                'db_table': 'TIPO_STATUS_ANIMAL',
            },
        ),
        migrations.CreateModel(
            name='Responde',
            fields=[
                ('cpf_responsavel', models.ForeignKey(db_column='cpf_responsavel', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cliente.Responsavel')),
            ],
            options={
                'verbose_name': 'Responsável por Animal (Responde)',
                'verbose_name_plural': 'Responsáveis por Animais (Responde)',
                'db_table': 'RESPONDE',
            },
        ),
        migrations.CreateModel(
            name='StatusAnimal',
            fields=[
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cliente.TipoStatusAnimal')),
            ],
            options={
                'verbose_name': 'Status do Animal',
                'verbose_name_plural': 'Status dos Animais',
                'db_table': 'STATUS_ANIMAL',
            },
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('cpf_cliente', models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cliente.Cliente')),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Telefone do Cliente',
                'verbose_name_plural': 'Telefones dos Clientes',
                'db_table': 'TELEFONE_CLIENTE',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_cliente',
            field=models.ForeignKey(db_column='id_tipo_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.TipoCliente'),
        ),
        migrations.AddField(
            model_name='animal',
            name='cpf_cliente',
            field=models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='telefonecliente',
            unique_together={('cpf_cliente', 'telefone')},
        ),
        migrations.AddField(
            model_name='statusanimal',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Animal'),
        ),
        migrations.AddField(
            model_name='responde',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Animal'),
        ),
        migrations.AlterUniqueTogether(
            name='statusanimal',
            unique_together={('id_status', 'id_animal')},
        ),
        migrations.AlterUniqueTogether(
            name='responde',
            unique_together={('cpf_responsavel', 'id_animal')},
        ),
    ]
