# Generated by Django 2.0.6 on 2018-10-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20181021_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
