# Generated by Django 2.0.6 on 2018-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20181025_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
