# Generated by Django 2.0.6 on 2018-11-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_auto_20181102_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cpf_cliente',
            field=models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='animal_cliente', to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_tipo_cliente',
            field=models.ForeignKey(db_column='id_tipo_cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_tipo_cliente', to='cliente.TipoCliente'),
        ),
        migrations.AlterField(
            model_name='fichaanimal',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ficha_animal', to='cliente.Animal'),
        ),
        migrations.AlterField(
            model_name='responde',
            name='cpf_responsavel',
            field=models.OneToOneField(db_column='cpf_responsavel', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responde_responsavel', serialize=False, to='cliente.Responsavel'),
        ),
        migrations.AlterField(
            model_name='responde',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, related_name='responde_animal', to='cliente.Animal'),
        ),
        migrations.AlterField(
            model_name='statusanimal',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_animal_animal', to='cliente.Animal'),
        ),
        migrations.AlterField(
            model_name='statusanimal',
            name='id_status',
            field=models.OneToOneField(db_column='id_status', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='status_animal_tipo_status', serialize=False, to='cliente.TipoStatusAnimal'),
        ),
        migrations.AlterField(
            model_name='telefonecliente',
            name='cpf_cliente',
            field=models.OneToOneField(db_column='cpf_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='telefone_cliente_cliente', serialize=False, to='cliente.Cliente'),
        ),
    ]
