# Generated by Django 2.0.6 on 2018-11-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_auto_20181104_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responde',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, related_name='responde_animal', to='cliente.Animal'),
        ),
    ]
