# Generated by Django 2.0.6 on 2018-11-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20181104_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='cpf_cliente',
        ),
        migrations.AddField(
            model_name='animal',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='animal_cliente', to='cliente.Cliente'),
        ),
    ]
