# Generated by Django 2.0.6 on 2018-06-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>', max_length=150, unique=True, verbose_name='Login'),
        ),
    ]
