# Generated by Django 2.0.6 on 2018-11-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargofuncionario',
            name='id_cargo',
            field=models.OneToOneField(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cargofuncionario_cargo', serialize=False, to='usuarios.Cargo'),
        ),
        migrations.AlterField(
            model_name='cargofuncionario',
            name='id_func',
            field=models.ForeignKey(db_column='id_func', on_delete=django.db.models.deletion.CASCADE, related_name='cargofuncionario_funcionario', to='usuarios.Funcionario'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='id_funcionario',
            field=models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.CASCADE, related_name='veterinario_funcionario', to='usuarios.Funcionario'),
        ),
    ]
