# Generated by Django 2.0.6 on 2018-10-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feitopor',
            name='id_funcionario',
            field=models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Funcionario'),
        ),
        migrations.AddField(
            model_name='atendimentoprocestetico',
            name='id_proc_estetico',
            field=models.ForeignKey(db_column='id_proc_estetico', on_delete=django.db.models.deletion.DO_NOTHING, to='servicos.ProcedimentoEstetico'),
        ),
        migrations.AddField(
            model_name='atendimentoprocclinico',
            name='id_proc_clinico',
            field=models.ForeignKey(db_column='id_proc_clinico', on_delete=django.db.models.deletion.DO_NOTHING, to='servicos.ProcedimentoClinico'),
        ),
        migrations.AlterUniqueTogether(
            name='statusestadia',
            unique_together={('id_estadia', 'id_status')},
        ),
        migrations.AlterUniqueTogether(
            name='statusatendimento',
            unique_together={('id_atendimento', 'id_status')},
        ),
        migrations.AlterUniqueTogether(
            name='fichadiagnostico',
            unique_together={('id_diagnostico', 'id_ficha')},
        ),
        migrations.AlterUniqueTogether(
            name='feitopor',
            unique_together={('id_atendimento', 'id_funcionario')},
        ),
        migrations.AlterUniqueTogether(
            name='atendimentoprocestetico',
            unique_together={('id_atendimento', 'id_proc_estetico')},
        ),
        migrations.AlterUniqueTogether(
            name='atendimentoprocclinico',
            unique_together={('id_atendimento', 'id_proc_clinico')},
        ),
    ]
