# Generated by Django 2.0.6 on 2018-10-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20181020_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='id_google_agenda',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]