# Generated by Django 2.0.6 on 2018-11-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20181031_2042'),
        ('servicos', '0003_atendimento_id_google_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='cpf_cliente',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
