# Generated by Django 2.0.6 on 2018-11-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_atendimento_id_google_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='cpf_cliente',
            field=models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_cliente', to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='id_orcamento',
            field=models.ForeignKey(blank=True, db_column='id_orcamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_orcamento', to='servicos.Orcamento'),
        ),
        migrations.AlterField(
            model_name='atendimentoprocclinico',
            name='id_atendimento',
            field=models.OneToOneField(db_column='id_atendimento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='atendimentoprocclinico_atendimento', serialize=False, to='servicos.Atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimentoprocclinico',
            name='id_proc_clinico',
            field=models.ForeignKey(db_column='id_proc_clinico', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentoprocclinico_procclinico', to='servicos.ProcedimentoClinico'),
        ),
        migrations.AlterField(
            model_name='atendimentoprocestetico',
            name='id_atendimento',
            field=models.OneToOneField(db_column='id_atendimento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='atendimentoprocestetico_atendimento', serialize=False, to='servicos.Atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimentoprocestetico',
            name='id_proc_estetico',
            field=models.ForeignKey(db_column='id_proc_estetico', on_delete=django.db.models.deletion.DO_NOTHING, related_name='atendimentoprocestetico_procestetico', to='servicos.ProcedimentoEstetico'),
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='id_proc_clinico',
            field=models.ForeignKey(db_column='id_proc_clinico', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizacaoo_procclinico', to='servicos.ProcedimentoClinico'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='id_atendimento',
            field=models.ForeignKey(db_column='id_atendimento', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comissao_atendimento', to='servicos.Atendimento'),
        ),
        migrations.AlterField(
            model_name='diagnosticoanimal',
            name='id_tipo_diagnostico',
            field=models.ForeignKey(blank=True, db_column='id_tipo_diagnostico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnostico_tipodiagnostico', to='servicos.TipoDiagnostico'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, related_name='estadia_animal', to='cliente.Animal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, related_name='exame_animal', to='cliente.Animal'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='id_tipo_exame',
            field=models.ForeignKey(db_column='id_tipo_exame', on_delete=django.db.models.deletion.DO_NOTHING, related_name='exame_id_tipo_exame', to='servicos.TipoExame'),
        ),
        migrations.AlterField(
            model_name='feitopor',
            name='id_atendimento',
            field=models.OneToOneField(db_column='id_atendimento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feitopor_atendimento', serialize=False, to='servicos.Atendimento'),
        ),
        migrations.AlterField(
            model_name='feitopor',
            name='id_funcionario',
            field=models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.CASCADE, related_name='feitopor_funcionario', to='usuarios.Funcionario'),
        ),
        migrations.AlterField(
            model_name='fichadiagnostico',
            name='id_diagnostico',
            field=models.OneToOneField(db_column='id_diagnostico', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fichadiagnostico_diagnostico', serialize=False, to='servicos.DiagnosticoAnimal'),
        ),
        migrations.AlterField(
            model_name='fichadiagnostico',
            name='id_ficha',
            field=models.ForeignKey(db_column='id_ficha', on_delete=django.db.models.deletion.CASCADE, related_name='fichadiagnostico_ficha', to='cliente.FichaAnimal'),
        ),
        migrations.AlterField(
            model_name='procedimentoclinico',
            name='id_tipo_proc',
            field=models.ForeignKey(db_column='id_tipo_proc', on_delete=django.db.models.deletion.DO_NOTHING, related_name='procclinico_tipoprocclinico', to='servicos.TipoProcedimento'),
        ),
        migrations.AlterField(
            model_name='statusatendimento',
            name='id_atendimento',
            field=models.OneToOneField(db_column='id_atendimento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statusatendimento_atendimento', serialize=False, to='servicos.Atendimento'),
        ),
        migrations.AlterField(
            model_name='statusatendimento',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.DO_NOTHING, related_name='statusatendimento_status', to='servicos.TipoStatusAtendimento'),
        ),
        migrations.AlterField(
            model_name='statusestadia',
            name='id_estadia',
            field=models.OneToOneField(db_column='id_estadia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statusestadia_estadia', serialize=False, to='servicos.Estadia'),
        ),
        migrations.AlterField(
            model_name='statusestadia',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.DO_NOTHING, related_name='statusestadia_status', to='servicos.TipoStatusEstadia'),
        ),
    ]
