# Generated by Django 2.0.6 on 2018-11-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20181104_1500'),
        ('servicos', '0004_auto_20181104_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='cpf_cliente',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id_animal',
            field=models.ForeignKey(db_column='id_animal', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_cliente', to='cliente.Animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame',
            name='descricao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
