# Generated by Django 2.0.6 on 2018-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_auto_20181110_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoanimal',
            name='booleano',
            field=models.BooleanField(default=False),
        ),
    ]
