# Generated by Django 2.0.6 on 2018-11-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_auto_20181116_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
